[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Zlib"
]
deny = [
    "GPL-3.0",
    "AGPL-3.0",
    "LGPL-3.0",
    "Unlicense",
]

[sources]
allow-registry = ["crates.io"]
allow-git = []

[advisories]
deny-warnings = true

[bans]
multiple-versions = "warn"
wildcards = "deny"

[vulnerabilities]
severity-threshold = "low"