name: CI/CD with Cargo Publish

on:
  push:
    branches:
      - main 
      - master

jobs:
  build_and_publish:
    name: Build, Test and Publish
    runs-on: ubuntu-latest
    environment: crates-io

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
   
      - name: Install Additional Tools
        run: |
          cargo install cargo-audit --force
          cargo install cargo-deny --force
          cargo install cargo-nextest --force

      - name: Run cargo-audit
        run: cargo audit

      - name: Run cargo-deny check
        run: cargo deny check --config deny.toml

      - name: Run tests with cargo-nextest all features
        run: cargo nextest run --all-features

      - name: Publish to Crates.io
        if: success()
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: cargo publish --token $CRATES_IO_TOKEN