name: Count test cases & publish badge

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  count-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Rust (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Build tests (compile only)
        run: |
          cargo test --all --no-run || true

      - name: Count test cases
        id: count_tests
        run: |
          count=$(cargo test --all -- --list 2>/dev/null | grep -E '^[[:alnum:]_].*' | grep -v '^$' | wc -l | tr -d ' ')
          echo "count=$count" >> $GITHUB_OUTPUT

      - name: Create badge JSON
        run: |
          mkdir -p badges
          COUNT=${{ steps.count_tests.outputs.count }}
          if [ "$COUNT" -eq "0" ]; then COLOR="lightgrey"; elif [ "$COUNT" -lt "10" ]; then COLOR="yellow"; else COLOR="brightgreen"; fi
          cat > badges/test-cases.json <<EOF
{"schemaVersion":1,"label":"test-cases","message":"${COUNT}","color":"${COLOR}"}
EOF

      - name: Push to gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COUNT: ${{ steps.count_tests.outputs.count }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # checkout gh-pages or create if it doesn't exist
          if git ls-remote --exit-code origin gh-pages; then
            git fetch origin gh-pages:gh-pages
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi

          # Remove everything (clean branch) and copy badges
          git rm -rf . || true
          mkdir -p badges
          cp -r ${GITHUB_WORKSPACE}/badges/* badges/

          git add badges/test-cases.json
          git commit -m "Update test-cases badge: $COUNT" || echo "No changes to commit"
          git push -u origin gh-pages --force
