name: Update Tests Badge

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write
  
jobs:
  create_badge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      
      - name: Install pasops CLI
        run: cargo install pasops --force
      
      - name: Checkout Badges Repository
        uses: actions/checkout@v5
        with:
          repository: pas2rust/badges
          path: badges
          token: ${{ secrets.BADGE_TOKEN }}

      - name: Generate Badge
        run: |
          pasops tests-badges --badge-name badges/zipher-tests.svg --label tests --color success --logo testcafe
        
      - name: Auto-Commit Badge to Badges Repository
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: Update zipher test count badge"
          file_pattern: 'badges/zipher-tests.svg'
          repository: badges
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_options: '--allow-empty'
          github-token: ${{ secrets.BADGE_TOKEN }}