name: Count Tests and Generate Badge

on:
  push:
    branches:
      - main
      - master

jobs:
  update_test_badge:
    runs-on: ubuntu-latest
    environment: badges
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install pasops CLI
        run: cargo install pasops --force

      - name: Setup Git Identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run pasops test-badges Command (create badge with count tests)
        env:
          GITHUB_TOKEN: ${{ secrets.BADGE_TOKEN }}
        run: |
          pasops tests-badges \
            --user pas2rust \
            --token $GITHUB_TOKEN \
            --remote origin \
            --branch master \
            --badge-name zipher-tests.svg \
            --label tests \
            --color success \
            --logo rust

