name: Update Tests Badge

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  create_badge:
    runs-on: ubuntu-latest
    environment: badges
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install pasops CLI
        run: cargo install pasops --force

      - name: Checkout Badges Repository
        uses: actions/checkout@v5
        with:
          repository: pas2rust/badges
          path: badges
          token: ${{ secrets.BADGE_TOKEN }}

      - name: Generate Badge
        run: |
          pasops tests-badges --badge-name zipher-tests.svg --label tests --color success --logo testcafe
          mv zipher-tests.svg badges/

      - name: List files in badges directory
        run: |
          cd badges
          ls -la

      - name: Debug - Check what was created
        run: |
          echo "File created?"
          ls -la badges/zipher-tests.svg || echo "File not found 404"
          echo "Content:"
          cat badges/zipher-tests.svg || echo "cat file error"

      - name: Force Commit to Badges Repository
        run: |
          cd badges
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add zipher-tests.svg
          git commit -m "chore: Update zipher test count badge" --allow-empty
          git push

      - name: Verify commit
        run: |
          cd badges
          git log --oneline -3